### ISSUE TITLE
Damage plums

### ISSUE THREAD

**Issue by rdntcntrl** [rdntcntrl/ratoa_gamecode#13]
Add damage plums as an option.
Should be possible to disable it server-side as well as locally.
Locally it would be nice if it could be enabled selectively for weapons with variable damage (splash damage weapons, SG, ..)

**Comment by kwadroke** [comment]
Maybe borrow code from the Aftershock Mod since it has the same license (GPL 2.0)?

https://github.com/pbrochart/oaunofficial/search?q=damageplum

**Comment by kwadroke** [comment]
Looks good!
