### ISSUE TITLE
Feature: CPM movement

### ISSUE THREAD

**Issue by oitzujoey** [rdntcntrl/ratoa_gamecode#3]
I can add easily add this, especially since you have done most of the work. The main things that would be changed are acceleration and wishspeed constants, step-up, Xonotic air control (GPLv2), and a new cvar to change the mode. If you are low on cvars, a variable with a name like g_movement can select VQ3, Rat mode, and CPM.

Do you think there would be any licensing concerns with this?
Is this something you would even want in Ratmod?

**Comment by rdntcntrl** [comment]
Sure, that would be cool! Just be sure that you don't add any additional serverinfo cvars if at all possible. Things like `g_ratPhysics` are used to set a flag in `g_ratFlags`, which is not supposed to be set manually but is the serverinfo cvar that clients use to determine these sorts of server settings.
